import type { Workout, Exercise } from '@/types'

export const WORKOUTS: Workout[] = [
  {
    id: 'push-day-1',
    name: 'Push Day — Chest & Shoulders',
    description: 'Classic push day targeting chest, shoulders, and triceps for maximum upper body development.',
    muscleGroups: ['Chest', 'Shoulders', 'Triceps'],
    duration: 60,
    difficulty: 'intermediate',
    category: 'Push',
    split: 'PPL',
    exercises: [
      { id: 'e1', name: 'Barbell Bench Press', sets: 4, reps: '6-8', rest: 120, notes: 'Control the eccentric, pause at chest', muscleGroup: 'Chest', equipment: 'Barbell', difficulty: 'intermediate' },
      { id: 'e2', name: 'Incline Dumbbell Press', sets: 3, reps: '8-10', rest: 90, notes: 'Slight arch, retract scapula', muscleGroup: 'Chest', equipment: 'Dumbbells', difficulty: 'intermediate' },
      { id: 'e3', name: 'Cable Chest Fly', sets: 3, reps: '12-15', rest: 60, notes: 'Full stretch at bottom, squeeze at top', muscleGroup: 'Chest', equipment: 'Cable', difficulty: 'beginner' },
      { id: 'e4', name: 'Overhead Press', sets: 4, reps: '6-8', rest: 120, notes: 'Brace core, drive through heels', muscleGroup: 'Shoulders', equipment: 'Barbell', difficulty: 'intermediate' },
      { id: 'e5', name: 'Lateral Raises', sets: 4, reps: '12-15', rest: 60, notes: 'Slight forward lean, lead with elbows', muscleGroup: 'Shoulders', equipment: 'Dumbbells', difficulty: 'beginner' },
      { id: 'e6', name: 'Tricep Pushdown', sets: 3, reps: '12-15', rest: 60, notes: 'Full extension, squeeze at bottom', muscleGroup: 'Triceps', equipment: 'Cable', difficulty: 'beginner' },
      { id: 'e7', name: 'Overhead Tricep Extension', sets: 3, reps: '10-12', rest: 60, notes: 'Keep elbows in, full range', muscleGroup: 'Triceps', equipment: 'Dumbbells', difficulty: 'beginner' },
    ],
  },
  {
    id: 'pull-day-1',
    name: 'Pull Day — V-Taper Back',
    description: 'Back and biceps focused session for building the coveted V-taper and thick back.',
    muscleGroups: ['Back', 'Biceps', 'Rear Delts'],
    duration: 65,
    difficulty: 'intermediate',
    category: 'Pull',
    split: 'PPL',
    exercises: [
      { id: 'e1', name: 'Pull-Ups / Lat Pulldown', sets: 4, reps: '6-10', rest: 120, notes: 'Full dead hang, pull to chest', muscleGroup: 'Back', equipment: 'Pull-up Bar', difficulty: 'intermediate' },
      { id: 'e2', name: 'Barbell Row', sets: 4, reps: '6-8', rest: 120, notes: 'Chest up, row to lower chest', muscleGroup: 'Back', equipment: 'Barbell', difficulty: 'intermediate' },
      { id: 'e3', name: 'Seated Cable Row', sets: 3, reps: '10-12', rest: 90, notes: 'Drive elbows back, squeeze shoulder blades', muscleGroup: 'Back', equipment: 'Cable', difficulty: 'beginner' },
      { id: 'e4', name: 'Straight Arm Pulldown', sets: 3, reps: '12-15', rest: 60, notes: 'Isolates lats, slight forward lean', muscleGroup: 'Back', equipment: 'Cable', difficulty: 'beginner' },
      { id: 'e5', name: 'Face Pulls', sets: 3, reps: '15-20', rest: 60, notes: 'External rotation, protect shoulder health', muscleGroup: 'Rear Delts', equipment: 'Cable', difficulty: 'beginner' },
      { id: 'e6', name: 'Barbell Curl', sets: 3, reps: '8-10', rest: 90, notes: 'No swinging, full supination at top', muscleGroup: 'Biceps', equipment: 'Barbell', difficulty: 'beginner' },
      { id: 'e7', name: 'Hammer Curl', sets: 3, reps: '10-12', rest: 60, notes: 'Neutral grip targets brachialis', muscleGroup: 'Biceps', equipment: 'Dumbbells', difficulty: 'beginner' },
    ],
  },
  {
    id: 'leg-day-1',
    name: 'Leg Day — Quad Dominant',
    description: 'Quad-focused leg session to build powerful, sculpted legs and glutes.',
    muscleGroups: ['Quads', 'Glutes', 'Hamstrings', 'Calves'],
    duration: 70,
    difficulty: 'intermediate',
    category: 'Legs',
    split: 'PPL',
    exercises: [
      { id: 'e1', name: 'Barbell Back Squat', sets: 4, reps: '5-7', rest: 180, notes: 'Break parallel, knees track toes', muscleGroup: 'Quads', equipment: 'Barbell', difficulty: 'intermediate' },
      { id: 'e2', name: 'Romanian Deadlift', sets: 4, reps: '8-10', rest: 120, notes: 'Hinge at hips, feel hamstring stretch', muscleGroup: 'Hamstrings', equipment: 'Barbell', difficulty: 'intermediate' },
      { id: 'e3', name: 'Leg Press', sets: 3, reps: '10-12', rest: 90, notes: 'Full range, feet shoulder width', muscleGroup: 'Quads', equipment: 'Machine', difficulty: 'beginner' },
      { id: 'e4', name: 'Walking Lunges', sets: 3, reps: '12 each', rest: 90, notes: 'Long stride, knee above ankle', muscleGroup: 'Quads', equipment: 'Dumbbells', difficulty: 'beginner' },
      { id: 'e5', name: 'Leg Curl', sets: 3, reps: '12-15', rest: 60, notes: 'Full extension, squeeze at top', muscleGroup: 'Hamstrings', equipment: 'Machine', difficulty: 'beginner' },
      { id: 'e6', name: 'Hip Thrust', sets: 3, reps: '12-15', rest: 90, notes: 'Drive through heels, squeeze glutes at top', muscleGroup: 'Glutes', equipment: 'Barbell', difficulty: 'beginner' },
      { id: 'e7', name: 'Calf Raises', sets: 4, reps: '15-20', rest: 45, notes: 'Full range, pause at top', muscleGroup: 'Calves', equipment: 'Machine', difficulty: 'beginner' },
    ],
  },
  {
    id: 'olympus-shoulders',
    name: 'Olympus Shoulder Protocol',
    description: 'The legendary shoulder session for building boulder caps and 3D deltoids worthy of Mount Olympus.',
    muscleGroups: ['Shoulders', 'Traps', 'Triceps'],
    duration: 55,
    difficulty: 'advanced',
    category: 'Shoulders',
    isFeatured: true,
    exercises: [
      { id: 'e1', name: 'Standing Military Press', sets: 5, reps: '4-6', rest: 180, notes: 'Maximum overhead strength builder', muscleGroup: 'Shoulders', equipment: 'Barbell', difficulty: 'advanced' },
      { id: 'e2', name: 'Arnold Press', sets: 4, reps: '8-10', rest: 90, notes: 'Rotate for full delt recruitment', muscleGroup: 'Shoulders', equipment: 'Dumbbells', difficulty: 'intermediate' },
      { id: 'e3', name: 'Cable Lateral Raises', sets: 4, reps: '15-20', rest: 60, notes: 'Constant tension, slight forward lean', muscleGroup: 'Shoulders', equipment: 'Cable', difficulty: 'beginner' },
      { id: 'e4', name: 'Rear Delt Fly Machine', sets: 4, reps: '12-15', rest: 60, notes: 'Full range, build 3D rear delts', muscleGroup: 'Rear Delts', equipment: 'Machine', difficulty: 'beginner' },
      { id: 'e5', name: 'Upright Row', sets: 3, reps: '10-12', rest: 60, notes: 'Wide grip for lateral delt emphasis', muscleGroup: 'Shoulders', equipment: 'Barbell', difficulty: 'intermediate' },
      { id: 'e6', name: 'Shrugs', sets: 3, reps: '12-15', rest: 60, notes: 'Heavy weight, hold at top', muscleGroup: 'Traps', equipment: 'Dumbbells', difficulty: 'beginner' },
      { id: 'e7', name: 'Drop Set Lateral Raises', sets: 3, reps: '10+10+10', rest: 90, notes: 'Triple drop set to failure for a nasty pump', muscleGroup: 'Shoulders', equipment: 'Dumbbells', difficulty: 'advanced' },
    ],
  },
  {
    id: 'v-taper-back',
    name: 'V-Taper Back Destroyer',
    description: 'Build the wide, dramatic back that creates the coveted V-taper silhouette.',
    muscleGroups: ['Lats', 'Rhomboids', 'Rear Delts', 'Biceps'],
    duration: 60,
    difficulty: 'advanced',
    category: 'Back',
    isFeatured: true,
    exercises: [
      { id: 'e1', name: 'Weighted Pull-Ups', sets: 5, reps: '5-7', rest: 180, notes: 'Full dead hang, chest to bar', muscleGroup: 'Back', equipment: 'Pull-up Bar', difficulty: 'advanced' },
      { id: 'e2', name: 'Wide Grip Lat Pulldown', sets: 4, reps: '8-10', rest: 90, notes: 'Lean slightly back, pull to upper chest', muscleGroup: 'Back', equipment: 'Cable', difficulty: 'intermediate' },
      { id: 'e3', name: 'T-Bar Row', sets: 4, reps: '8-10', rest: 120, notes: 'Chest supported, massive back thickness', muscleGroup: 'Back', equipment: 'T-Bar', difficulty: 'intermediate' },
      { id: 'e4', name: 'Single Arm Dumbbell Row', sets: 3, reps: '10-12 each', rest: 90, notes: 'Full stretch, row to hip', muscleGroup: 'Back', equipment: 'Dumbbells', difficulty: 'beginner' },
      { id: 'e5', name: 'Straight Arm Cable Pulldown', sets: 3, reps: '15-20', rest: 60, notes: 'Lat isolation, arc motion', muscleGroup: 'Back', equipment: 'Cable', difficulty: 'beginner' },
      { id: 'e6', name: 'Cable Face Pull', sets: 3, reps: '20-25', rest: 45, notes: 'Rear delt & external rotator health', muscleGroup: 'Rear Delts', equipment: 'Cable', difficulty: 'beginner' },
      { id: 'e7', name: 'Chin-Ups', sets: 3, reps: 'To failure', rest: 90, notes: 'Supinated grip for bicep involvement', muscleGroup: 'Back', equipment: 'Pull-up Bar', difficulty: 'intermediate' },
    ],
  },
  {
    id: 'chest-architecture',
    name: 'Chest Architecture',
    description: 'Scientific chest program for building a full, thick, and striated chest from all angles.',
    muscleGroups: ['Chest', 'Shoulders', 'Triceps'],
    duration: 60,
    difficulty: 'intermediate',
    category: 'Chest',
    isFeatured: true,
    exercises: [
      { id: 'e1', name: 'Flat Barbell Bench Press', sets: 5, reps: '5-7', rest: 180, notes: 'Primary mass builder, full arch', muscleGroup: 'Chest', equipment: 'Barbell', difficulty: 'intermediate' },
      { id: 'e2', name: 'Incline Barbell Press', sets: 4, reps: '8-10', rest: 120, notes: '30° incline for upper chest', muscleGroup: 'Chest', equipment: 'Barbell', difficulty: 'intermediate' },
      { id: 'e3', name: 'Decline Press', sets: 3, reps: '10-12', rest: 90, notes: 'Lower chest fullness', muscleGroup: 'Chest', equipment: 'Barbell', difficulty: 'intermediate' },
      { id: 'e4', name: 'Cable Crossover', sets: 3, reps: '12-15', rest: 60, notes: 'Cross hands at bottom for full contraction', muscleGroup: 'Chest', equipment: 'Cable', difficulty: 'beginner' },
      { id: 'e5', name: 'Dumbbell Fly', sets: 3, reps: '12-15', rest: 60, notes: 'Deep stretch, don\'t lock elbows', muscleGroup: 'Chest', equipment: 'Dumbbells', difficulty: 'beginner' },
      { id: 'e6', name: 'Dips (Chest Focused)', sets: 3, reps: '10-12', rest: 90, notes: 'Forward lean to target chest', muscleGroup: 'Chest', equipment: 'Dip Bars', difficulty: 'intermediate' },
    ],
  },
  {
    id: 'core-destroyer',
    name: 'Core Destroyer',
    description: 'High-intensity core session targeting all layers of the abdominal wall for a carved midsection.',
    muscleGroups: ['Abs', 'Obliques', 'Core'],
    duration: 30,
    difficulty: 'intermediate',
    category: 'Core',
    exercises: [
      { id: 'e1', name: 'Hanging Leg Raises', sets: 4, reps: '12-15', rest: 60, notes: 'Control the descent, no swinging', muscleGroup: 'Abs', equipment: 'Pull-up Bar', difficulty: 'intermediate' },
      { id: 'e2', name: 'Cable Crunch', sets: 4, reps: '15-20', rest: 45, notes: 'Round lower back at bottom', muscleGroup: 'Abs', equipment: 'Cable', difficulty: 'beginner' },
      { id: 'e3', name: 'Ab Wheel Rollout', sets: 3, reps: '8-12', rest: 60, notes: 'Full extension if possible', muscleGroup: 'Abs', equipment: 'Ab Wheel', difficulty: 'advanced' },
      { id: 'e4', name: 'Russian Twists', sets: 3, reps: '20 each', rest: 45, notes: 'Elevate feet for extra difficulty', muscleGroup: 'Obliques', equipment: 'Bodyweight', difficulty: 'beginner' },
      { id: 'e5', name: 'Plank', sets: 3, reps: '60s', rest: 45, notes: 'Squeeze everything, breathe', muscleGroup: 'Core', equipment: 'Bodyweight', difficulty: 'beginner' },
      { id: 'e6', name: 'Dragon Flag', sets: 3, reps: '5-8', rest: 90, notes: 'Advanced movement, straight body throughout', muscleGroup: 'Abs', equipment: 'Bench', difficulty: 'advanced' },
    ],
  },
  {
    id: 'full-body-beginner',
    name: 'Full Body — Beginner',
    description: 'Perfect starting point for beginners. Hits every major muscle group with simple, effective movements.',
    muscleGroups: ['Full Body'],
    duration: 45,
    difficulty: 'beginner',
    category: 'Full Body',
    exercises: [
      { id: 'e1', name: 'Goblet Squat', sets: 3, reps: '10-12', rest: 90, notes: 'Chest up, sit between knees', muscleGroup: 'Legs', equipment: 'Dumbbell', difficulty: 'beginner' },
      { id: 'e2', name: 'Push-Ups', sets: 3, reps: '8-15', rest: 60, notes: 'Full range, body straight as a board', muscleGroup: 'Chest', equipment: 'Bodyweight', difficulty: 'beginner' },
      { id: 'e3', name: 'Dumbbell Row', sets: 3, reps: '10 each', rest: 60, notes: 'Brace on bench, pull elbow back', muscleGroup: 'Back', equipment: 'Dumbbell', difficulty: 'beginner' },
      { id: 'e4', name: 'Dumbbell Press', sets: 3, reps: '10-12', rest: 60, notes: 'Feet flat, controlled movement', muscleGroup: 'Shoulders', equipment: 'Dumbbells', difficulty: 'beginner' },
      { id: 'e5', name: 'Romanian Deadlift', sets: 3, reps: '10-12', rest: 90, notes: 'Feel hamstring stretch each rep', muscleGroup: 'Hamstrings', equipment: 'Dumbbells', difficulty: 'beginner' },
      { id: 'e6', name: 'Plank', sets: 3, reps: '30-45s', rest: 45, notes: 'Core tight, don\'t hold breath', muscleGroup: 'Core', equipment: 'Bodyweight', difficulty: 'beginner' },
    ],
  },
  {
    id: 'upper-body-hypertrophy',
    name: 'Upper Body Hypertrophy',
    description: 'High volume upper body session for maximum muscle growth across chest, back, and arms.',
    muscleGroups: ['Chest', 'Back', 'Shoulders', 'Arms'],
    duration: 75,
    difficulty: 'intermediate',
    category: 'Upper',
    split: 'Upper/Lower',
    exercises: [
      { id: 'e1', name: 'Incline Dumbbell Press', sets: 4, reps: '8-10', rest: 90, notes: 'Upper chest emphasis', muscleGroup: 'Chest', equipment: 'Dumbbells', difficulty: 'intermediate' },
      { id: 'e2', name: 'Lat Pulldown', sets: 4, reps: '8-10', rest: 90, notes: 'Pull to upper chest, full stretch', muscleGroup: 'Back', equipment: 'Cable', difficulty: 'beginner' },
      { id: 'e3', name: 'Dumbbell Shoulder Press', sets: 3, reps: '10-12', rest: 75, notes: '90° at bottom, full lockout', muscleGroup: 'Shoulders', equipment: 'Dumbbells', difficulty: 'beginner' },
      { id: 'e4', name: 'Cable Row', sets: 3, reps: '10-12', rest: 75, notes: 'Chest up, full stretch forward', muscleGroup: 'Back', equipment: 'Cable', difficulty: 'beginner' },
      { id: 'e5', name: 'Dumbbell Curl', sets: 3, reps: '12-15', rest: 60, notes: 'Supinate at top', muscleGroup: 'Biceps', equipment: 'Dumbbells', difficulty: 'beginner' },
      { id: 'e6', name: 'Skull Crushers', sets: 3, reps: '12-15', rest: 60, notes: 'Lower to forehead, elbow steady', muscleGroup: 'Triceps', equipment: 'EZ Bar', difficulty: 'intermediate' },
      { id: 'e7', name: 'Lateral Raises', sets: 3, reps: '15-20', rest: 45, notes: 'Pump finish for shoulders', muscleGroup: 'Shoulders', equipment: 'Dumbbells', difficulty: 'beginner' },
    ],
  },
  {
    id: 'lower-body-power',
    name: 'Lower Body Power',
    description: 'Power-focused lower body session for athletic performance and size.',
    muscleGroups: ['Quads', 'Hamstrings', 'Glutes', 'Calves'],
    duration: 65,
    difficulty: 'advanced',
    category: 'Lower',
    split: 'Upper/Lower',
    exercises: [
      { id: 'e1', name: 'Back Squat', sets: 5, reps: '5', rest: 180, notes: 'Belt optional, full depth', muscleGroup: 'Quads', equipment: 'Barbell', difficulty: 'advanced' },
      { id: 'e2', name: 'Deadlift', sets: 4, reps: '4-6', rest: 180, notes: 'Bar over mid-foot, drive floor away', muscleGroup: 'Hamstrings', equipment: 'Barbell', difficulty: 'advanced' },
      { id: 'e3', name: 'Bulgarian Split Squat', sets: 3, reps: '8-10 each', rest: 90, notes: 'Rear foot elevated, knee tracks toes', muscleGroup: 'Quads', equipment: 'Dumbbells', difficulty: 'intermediate' },
      { id: 'e4', name: 'Nordic Curl', sets: 3, reps: '5-8', rest: 90, notes: 'Eccentric only if needed', muscleGroup: 'Hamstrings', equipment: 'Bodyweight', difficulty: 'advanced' },
      { id: 'e5', name: 'Hip Thrust', sets: 3, reps: '10-12', rest: 90, notes: 'Full hip extension at top', muscleGroup: 'Glutes', equipment: 'Barbell', difficulty: 'intermediate' },
      { id: 'e6', name: 'Standing Calf Raise', sets: 5, reps: '15-20', rest: 45, notes: 'Full range, pause at top and bottom', muscleGroup: 'Calves', equipment: 'Machine', difficulty: 'beginner' },
    ],
  },
  {
    id: 'arm-annihilation',
    name: 'Arm Annihilation',
    description: 'Dedicated arm day for building massive biceps and horseshoe triceps.',
    muscleGroups: ['Biceps', 'Triceps', 'Forearms'],
    duration: 45,
    difficulty: 'intermediate',
    category: 'Arms',
    exercises: [
      { id: 'e1', name: 'EZ Bar Curl', sets: 4, reps: '8-10', rest: 90, notes: 'Slight incline for long head', muscleGroup: 'Biceps', equipment: 'EZ Bar', difficulty: 'beginner' },
      { id: 'e2', name: 'Close Grip Bench Press', sets: 4, reps: '8-10', rest: 90, notes: 'Shoulder width grip, elbows tucked', muscleGroup: 'Triceps', equipment: 'Barbell', difficulty: 'intermediate' },
      { id: 'e3', name: 'Incline Dumbbell Curl', sets: 3, reps: '10-12', rest: 75, notes: 'Full stretch for long head', muscleGroup: 'Biceps', equipment: 'Dumbbells', difficulty: 'beginner' },
      { id: 'e4', name: 'Rope Pushdown', sets: 3, reps: '12-15', rest: 60, notes: 'Separate hands at bottom', muscleGroup: 'Triceps', equipment: 'Cable', difficulty: 'beginner' },
      { id: 'e5', name: 'Concentration Curl', sets: 3, reps: '12-15 each', rest: 60, notes: 'Elbow on inner thigh, peak squeeze', muscleGroup: 'Biceps', equipment: 'Dumbbell', difficulty: 'beginner' },
      { id: 'e6', name: 'Overhead Extension', sets: 3, reps: '12-15', rest: 60, notes: 'Long head stretch at top', muscleGroup: 'Triceps', equipment: 'Cable', difficulty: 'beginner' },
      { id: 'e7', name: 'Reverse Curl', sets: 3, reps: '12-15', rest: 45, notes: 'Forearm and brachialis', muscleGroup: 'Forearms', equipment: 'Barbell', difficulty: 'beginner' },
    ],
  },
  {
    id: 'greek-god-upper',
    name: 'Greek God Upper Body',
    description: 'The complete aesthetic upper body session. Broad shoulders, thick chest, wide back, peaked arms.',
    muscleGroups: ['Chest', 'Back', 'Shoulders', 'Arms'],
    duration: 90,
    difficulty: 'advanced',
    category: 'Full Upper',
    isFeatured: true,
    exercises: [
      { id: 'e1', name: 'Weighted Pull-Ups', sets: 4, reps: '6-8', rest: 120, notes: 'Width first priority', muscleGroup: 'Back', equipment: 'Pull-up Bar', difficulty: 'advanced' },
      { id: 'e2', name: 'Incline Barbell Press', sets: 4, reps: '6-8', rest: 120, notes: 'Upper chest dominance', muscleGroup: 'Chest', equipment: 'Barbell', difficulty: 'intermediate' },
      { id: 'e3', name: 'Standing Dumbbell Press', sets: 4, reps: '8-10', rest: 90, notes: 'Core stability, full range', muscleGroup: 'Shoulders', equipment: 'Dumbbells', difficulty: 'intermediate' },
      { id: 'e4', name: 'Cable Row', sets: 3, reps: '10-12', rest: 75, notes: 'Mid-back thickness', muscleGroup: 'Back', equipment: 'Cable', difficulty: 'beginner' },
      { id: 'e5', name: 'Cable Fly', sets: 3, reps: '12-15', rest: 60, notes: 'Full stretch for pec development', muscleGroup: 'Chest', equipment: 'Cable', difficulty: 'beginner' },
      { id: 'e6', name: 'Lateral Raise Drop Set', sets: 3, reps: '15+12+10', rest: 75, notes: 'Descend weight each set', muscleGroup: 'Shoulders', equipment: 'Dumbbells', difficulty: 'intermediate' },
      { id: 'e7', name: 'Barbell Curl', sets: 3, reps: '8-10', rest: 75, notes: 'Cheat slightly on last 2 reps', muscleGroup: 'Biceps', equipment: 'Barbell', difficulty: 'intermediate' },
      { id: 'e8', name: 'Dips', sets: 3, reps: 'To failure', rest: 75, notes: 'Lean forward for chest emphasis', muscleGroup: 'Triceps', equipment: 'Dip Bars', difficulty: 'intermediate' },
    ],
  },
  {
    id: 'hiit-conditioning',
    name: 'HIIT Conditioning',
    description: 'High intensity interval training for maximum fat burn and conditioning.',
    muscleGroups: ['Full Body', 'Cardio'],
    duration: 35,
    difficulty: 'advanced',
    category: 'Cardio',
    exercises: [
      { id: 'e1', name: 'Burpees', sets: 5, reps: '20s on / 10s off', rest: 0, notes: 'Maximum effort on active intervals', muscleGroup: 'Full Body', equipment: 'Bodyweight', difficulty: 'advanced' },
      { id: 'e2', name: 'Jump Squats', sets: 5, reps: '20s on / 10s off', rest: 0, notes: 'Explode up, land soft', muscleGroup: 'Legs', equipment: 'Bodyweight', difficulty: 'intermediate' },
      { id: 'e3', name: 'Mountain Climbers', sets: 5, reps: '20s on / 10s off', rest: 0, notes: 'Fast pace, hips level', muscleGroup: 'Core', equipment: 'Bodyweight', difficulty: 'intermediate' },
      { id: 'e4', name: 'Kettlebell Swings', sets: 5, reps: '20s on / 10s off', rest: 0, notes: 'Hip hinge power, not squat', muscleGroup: 'Full Body', equipment: 'Kettlebell', difficulty: 'intermediate' },
      { id: 'e5', name: 'Sprint in Place', sets: 5, reps: '20s on / 10s off', rest: 60, notes: 'Knees high, pump arms', muscleGroup: 'Full Body', equipment: 'Bodyweight', difficulty: 'intermediate' },
    ],
  },
  {
    id: 'mobility-recovery',
    name: 'Mobility & Recovery',
    description: 'Active recovery day with mobility drills, stretching, and movement quality work.',
    muscleGroups: ['Full Body', 'Flexibility'],
    duration: 40,
    difficulty: 'beginner',
    category: 'Recovery',
    exercises: [
      { id: 'e1', name: 'World\'s Greatest Stretch', sets: 2, reps: '5 each side', rest: 0, notes: 'Multi-joint opener, breathe into each position', muscleGroup: 'Full Body', equipment: 'Bodyweight', difficulty: 'beginner' },
      { id: 'e2', name: 'Hip 90/90 Stretch', sets: 2, reps: '60s each side', rest: 0, notes: 'Relax into position, don\'t force', muscleGroup: 'Hips', equipment: 'Bodyweight', difficulty: 'beginner' },
      { id: 'e3', name: 'Thoracic Rotation', sets: 2, reps: '10 each side', rest: 0, notes: 'From quadruped, rotate to ceiling', muscleGroup: 'Spine', equipment: 'Bodyweight', difficulty: 'beginner' },
      { id: 'e4', name: 'Lat Stretch', sets: 3, reps: '30s each', rest: 0, notes: 'Hanging or doorframe stretch', muscleGroup: 'Back', equipment: 'Pull-up Bar', difficulty: 'beginner' },
      { id: 'e5', name: 'Pigeon Pose', sets: 2, reps: '90s each side', rest: 0, notes: 'Critical for hip flexor & glute health', muscleGroup: 'Hips', equipment: 'Bodyweight', difficulty: 'beginner' },
      { id: 'e6', name: 'Shoulder Dislocations', sets: 3, reps: '15', rest: 0, notes: 'With band or broomstick, wide grip', muscleGroup: 'Shoulders', equipment: 'Band', difficulty: 'beginner' },
    ],
  },
  {
    id: 'glute-focus',
    name: 'Glute & Hamstring Sculpt',
    description: 'Targeted glute and hamstring session for shape, size, and strength.',
    muscleGroups: ['Glutes', 'Hamstrings'],
    duration: 50,
    difficulty: 'intermediate',
    category: 'Legs',
    exercises: [
      { id: 'e1', name: 'Barbell Hip Thrust', sets: 5, reps: '8-10', rest: 120, notes: 'Ribs down, squeeze at top', muscleGroup: 'Glutes', equipment: 'Barbell', difficulty: 'intermediate' },
      { id: 'e2', name: 'Romanian Deadlift', sets: 4, reps: '8-10', rest: 90, notes: 'Tension stays on hamstrings', muscleGroup: 'Hamstrings', equipment: 'Barbell', difficulty: 'intermediate' },
      { id: 'e3', name: 'Cable Kickback', sets: 3, reps: '15-20 each', rest: 60, notes: 'Posterior pelvic tilt at top', muscleGroup: 'Glutes', equipment: 'Cable', difficulty: 'beginner' },
      { id: 'e4', name: 'Sumo Squat', sets: 3, reps: '12-15', rest: 75, notes: 'Wide stance, toes out 45°', muscleGroup: 'Glutes', equipment: 'Dumbbell', difficulty: 'beginner' },
      { id: 'e5', name: 'Nordic Curl', sets: 3, reps: '5-8', rest: 90, notes: 'Best hamstring builder', muscleGroup: 'Hamstrings', equipment: 'Bodyweight', difficulty: 'advanced' },
      { id: 'e6', name: 'Glute Bridge', sets: 3, reps: '20', rest: 45, notes: 'Banded for extra tension', muscleGroup: 'Glutes', equipment: 'Bodyweight', difficulty: 'beginner' },
    ],
  },
  {
    id: 'power-complex',
    name: 'Power Complex',
    description: 'Explosive power training combining heavy compound lifts with plyometric movements.',
    muscleGroups: ['Full Body', 'Power'],
    duration: 60,
    difficulty: 'advanced',
    category: 'Power',
    exercises: [
      { id: 'e1', name: 'Hang Power Clean', sets: 5, reps: '3', rest: 180, notes: 'Violent hip extension, fast elbows', muscleGroup: 'Full Body', equipment: 'Barbell', difficulty: 'advanced' },
      { id: 'e2', name: 'Push Press', sets: 4, reps: '4-5', rest: 150, notes: 'Leg drive then press', muscleGroup: 'Shoulders', equipment: 'Barbell', difficulty: 'advanced' },
      { id: 'e3', name: 'Box Jump', sets: 5, reps: '5', rest: 120, notes: 'Full extension at jump, soft landing', muscleGroup: 'Legs', equipment: 'Box', difficulty: 'intermediate' },
      { id: 'e4', name: 'Trap Bar Deadlift', sets: 4, reps: '4-6', rest: 180, notes: 'Vertical shins, chest up', muscleGroup: 'Full Body', equipment: 'Trap Bar', difficulty: 'intermediate' },
      { id: 'e5', name: 'Plyo Push-Ups', sets: 4, reps: '6-8', rest: 90, notes: 'Explode off floor, clap if possible', muscleGroup: 'Chest', equipment: 'Bodyweight', difficulty: 'advanced' },
    ],
  },
  {
    id: 'home-workout-1',
    name: 'Home Warrior — No Equipment',
    description: 'Full body bodyweight workout you can do anywhere, no equipment needed.',
    muscleGroups: ['Full Body'],
    duration: 40,
    difficulty: 'beginner',
    category: 'Home',
    exercises: [
      { id: 'e1', name: 'Push-Ups', sets: 4, reps: '15-20', rest: 60, notes: 'Standard or kneeling variation', muscleGroup: 'Chest', equipment: 'Bodyweight', difficulty: 'beginner' },
      { id: 'e2', name: 'Bodyweight Squats', sets: 4, reps: '20', rest: 60, notes: 'Parallel depth, arms forward', muscleGroup: 'Legs', equipment: 'Bodyweight', difficulty: 'beginner' },
      { id: 'e3', name: 'Inverted Row', sets: 3, reps: '10-15', rest: 60, notes: 'Under table or low bar', muscleGroup: 'Back', equipment: 'Bodyweight', difficulty: 'beginner' },
      { id: 'e4', name: 'Pike Push-Ups', sets: 3, reps: '10-12', rest: 60, notes: 'Hips high, lower head to ground', muscleGroup: 'Shoulders', equipment: 'Bodyweight', difficulty: 'beginner' },
      { id: 'e5', name: 'Lunges', sets: 3, reps: '12 each', rest: 60, notes: 'Upright torso, front knee over ankle', muscleGroup: 'Legs', equipment: 'Bodyweight', difficulty: 'beginner' },
      { id: 'e6', name: 'Hollow Body Hold', sets: 3, reps: '30-45s', rest: 45, notes: 'Lower back pressed to floor', muscleGroup: 'Core', equipment: 'Bodyweight', difficulty: 'intermediate' },
      { id: 'e7', name: 'Glute Bridge', sets: 3, reps: '20', rest: 45, notes: 'Squeeze at top, slow descent', muscleGroup: 'Glutes', equipment: 'Bodyweight', difficulty: 'beginner' },
    ],
  },
  {
    id: 'advanced-chest-back',
    name: 'Advanced Chest & Back Superset',
    description: 'Antagonist superset training for maximum pump and time efficiency.',
    muscleGroups: ['Chest', 'Back'],
    duration: 55,
    difficulty: 'advanced',
    category: 'Chest & Back',
    exercises: [
      { id: 'e1', name: 'Bench Press + Bent Over Row', sets: 4, reps: '8 + 8', rest: 90, notes: 'Superset, no rest between exercises', muscleGroup: 'Chest/Back', equipment: 'Barbell', difficulty: 'advanced' },
      { id: 'e2', name: 'Incline Press + Pulldowns', sets: 4, reps: '10 + 10', rest: 75, notes: 'Superset for upper chest & width', muscleGroup: 'Chest/Back', equipment: 'Mixed', difficulty: 'intermediate' },
      { id: 'e3', name: 'Cable Fly + Face Pull', sets: 3, reps: '15 + 20', rest: 60, notes: 'Isolation superset', muscleGroup: 'Chest/Rear Delt', equipment: 'Cable', difficulty: 'beginner' },
      { id: 'e4', name: 'Push-Up + Pull-Up', sets: 3, reps: 'To failure', rest: 90, notes: 'Classic antagonist superset', muscleGroup: 'Chest/Back', equipment: 'Bodyweight', difficulty: 'intermediate' },
    ],
  },
  {
    id: 'beginner-push',
    name: 'Beginner Push Day',
    description: 'Simple and effective push session for those starting out.',
    muscleGroups: ['Chest', 'Shoulders', 'Triceps'],
    duration: 45,
    difficulty: 'beginner',
    category: 'Push',
    exercises: [
      { id: 'e1', name: 'Dumbbell Bench Press', sets: 3, reps: '10-12', rest: 90, notes: 'Shoulder width grip, controlled', muscleGroup: 'Chest', equipment: 'Dumbbells', difficulty: 'beginner' },
      { id: 'e2', name: 'Machine Chest Press', sets: 3, reps: '10-12', rest: 75, notes: 'Good for learning the pattern', muscleGroup: 'Chest', equipment: 'Machine', difficulty: 'beginner' },
      { id: 'e3', name: 'Dumbbell Shoulder Press', sets: 3, reps: '10-12', rest: 75, notes: 'Seated for stability', muscleGroup: 'Shoulders', equipment: 'Dumbbells', difficulty: 'beginner' },
      { id: 'e4', name: 'Lateral Raises', sets: 3, reps: '12-15', rest: 60, notes: 'Light weight, full range', muscleGroup: 'Shoulders', equipment: 'Dumbbells', difficulty: 'beginner' },
      { id: 'e5', name: 'Tricep Pushdown', sets: 3, reps: '12-15', rest: 60, notes: 'Keep elbows pinned to sides', muscleGroup: 'Triceps', equipment: 'Cable', difficulty: 'beginner' },
    ],
  },
  {
    id: 'beginner-pull',
    name: 'Beginner Pull Day',
    description: 'Foundational pull movements for building back and bicep strength.',
    muscleGroups: ['Back', 'Biceps'],
    duration: 45,
    difficulty: 'beginner',
    category: 'Pull',
    exercises: [
      { id: 'e1', name: 'Assisted Pull-Up / Lat Pulldown', sets: 3, reps: '10-12', rest: 90, notes: 'Full stretch at top', muscleGroup: 'Back', equipment: 'Machine', difficulty: 'beginner' },
      { id: 'e2', name: 'Seated Cable Row', sets: 3, reps: '10-12', rest: 75, notes: 'Drive elbows back, don\'t lean', muscleGroup: 'Back', equipment: 'Cable', difficulty: 'beginner' },
      { id: 'e3', name: 'Dumbbell Row', sets: 3, reps: '10 each', rest: 75, notes: 'Support on bench', muscleGroup: 'Back', equipment: 'Dumbbell', difficulty: 'beginner' },
      { id: 'e4', name: 'Dumbbell Curl', sets: 3, reps: '10-12', rest: 60, notes: 'No swinging, controlled', muscleGroup: 'Biceps', equipment: 'Dumbbells', difficulty: 'beginner' },
      { id: 'e5', name: 'Reverse Fly', sets: 3, reps: '12-15', rest: 60, notes: 'Rear delts, slight bend in elbow', muscleGroup: 'Rear Delts', equipment: 'Dumbbells', difficulty: 'beginner' },
    ],
  },
]

export function getWorkoutById(id: string): Workout | undefined {
  return WORKOUTS.find(w => w.id === id)
}

export function getWorkoutsByCategory(category: string): Workout[] {
  if (category === 'All') return WORKOUTS
  return WORKOUTS.filter(w =>
    w.muscleGroups.some(g => g.toLowerCase().includes(category.toLowerCase())) ||
    w.category.toLowerCase().includes(category.toLowerCase())
  )
}

export function getFeaturedWorkouts(): Workout[] {
  return WORKOUTS.filter(w => w.isFeatured)
}

export function getBeginnerWorkouts(): Workout[] {
  return WORKOUTS.filter(w => w.difficulty === 'beginner')
}

export function getWorkoutsByDifficulty(difficulty: string): Workout[] {
  return WORKOUTS.filter(w => w.difficulty === difficulty)
}

export const WORKOUT_CATEGORIES = ['All', 'Chest', 'Back', 'Shoulders', 'Arms', 'Legs', 'Core', 'Full Body', 'Cardio']

export const SPLIT_SCHEDULES: Record<string, Record<string, string>> = {
  PPL: {
    Monday: 'push-day-1',
    Tuesday: 'pull-day-1',
    Wednesday: 'leg-day-1',
    Thursday: 'push-day-1',
    Friday: 'pull-day-1',
    Saturday: 'leg-day-1',
    Sunday: 'Rest',
  },
  'Upper/Lower': {
    Monday: 'upper-body-hypertrophy',
    Tuesday: 'lower-body-power',
    Wednesday: 'Rest',
    Thursday: 'upper-body-hypertrophy',
    Friday: 'lower-body-power',
    Saturday: 'core-destroyer',
    Sunday: 'Rest',
  },
  'Full Body': {
    Monday: 'full-body-beginner',
    Tuesday: 'Rest',
    Wednesday: 'full-body-beginner',
    Thursday: 'Rest',
    Friday: 'full-body-beginner',
    Saturday: 'hiit-conditioning',
    Sunday: 'Rest',
  },
  'Bro Split': {
    Monday: 'chest-architecture',
    Tuesday: 'v-taper-back',
    Wednesday: 'lower-body-power',
    Thursday: 'olympus-shoulders',
    Friday: 'arm-annihilation',
    Saturday: 'core-destroyer',
    Sunday: 'Rest',
  },
}
